##ddev-generated
image: ddev/ddev-gitpod-base:20240702

## -------------------------
## Define how Gitpod prepares & builds your project and how it can start the project’s development server(s).
## @see https://www.gitpod.io/docs/references/gitpod-yml#tasks
tasks:
  - init: |
      ddev start -y
      ddev composer install
      ddev npm install
      ddev npm run build
      ddev artisan key:generate
      ddev artisan migrate
    command: |
      ddev start -y
      gp ports await 8080 && gp preview $(gp url 8080)

## -------------------------
## Configure the VS Code editor.
## @see https://www.gitpod.io/docs/references/gitpod-yml#vscode
vscode:
  # Define a list of extensions which should be installed for users of this workspace.
  # Gitpod uses the [Open VSX registry](https://open-vsx.org/) to find extensions.
  extensions:
    - GitHub.vscode-pull-request-github
    - xdebug.php-debug
    - bmewburn.vscode-intelephense-client

## -------------------------
## Configure how Gitpod treats various ports your application may listen on.
## @see https://www.gitpod.io/docs/references/gitpod-yml#ports
ports:
  # Used by ddev - local db clients
  - port: 3306
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  # Currently un-notified and unsupported mailpit https port
  - port: 8027
    onOpen: ignore
  # Currently un-notified and unsupported phpmyadmin http port
  - port: 8036
    onOpen: ignore
  # Currently un-notified and unsupported phpmyadmin https port
  - port: 8037
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  # xhgui http port
  - port: 8143
    onOpen: ignore
  # xhgui https port
  - port: 8142
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore
  # Adminer http port
  - port: 9100
    onOpen: ignore
  # Adminer https port
  - port: 9101
    onOpen: ignore
  # projector port
  - port: 9999
    onOpen: open-browser

## -------------------------
## Configure continuous prebuilds for GitHub repositories
## @see https://www.gitpod.io/docs/references/gitpod-yml#github
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
